- name: Provision front VM
  hosts: front
  become: yes
  roles:
    - front

- name: Provision back VM
  hosts: back
  become: yes
  roles:
    - back

- name: Provision db VM
  hosts: db
  become: yes
  roles:
    - db

