- name: Mettre à jour les dépôts APT
  apt:
    update_cache: yes

- name: Installer MariaDB Server
  apt:
    name: mariadb-server
    state: present

- name: Démarrer et activer le service MariaDB
  service:
    name: mariadb
    state: started
    enabled: yes




